name: Monitor Horários Pure Pilates

on:
  schedule:
    - cron: '*/30 8-23 * * *'  # de 8h a 23h30 (UTC)
    - cron: '*/30 0-4 * * *'   # de 0h a 4h30 (UTC)
  
  # Permite execução manual
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run monitor script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python monitor_pilates.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add horarios_anteriores.json || true
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualizar horários monitorados [skip ci]" && git push)